### ISSUE TITLE
vite+vue3 会提示错误

### ISSUE THREAD

**Issue by lambert519** [wangeditor-team/wangEditor-for-vue3#8]
vite2.8 vue3.2
安装了@wangeditor/editor-for-vue@next

编辑器的config里面全是这个。
arguments: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:2:14)]
自定义粘贴和自定义弹窗都失效

**Comment by liuqh0609** [comment]
没有复现你的问题，我使用的是这个测试代码[editor-vue3-demo](https://github.com/liuqh0609/editor-vue3-demo)。
你可以查看一下，或者提供一个可以复现您这个问题的demo

**Comment by Corgis** [comment]
请问怎么拿 菜单栏  实例
下面代码拿的是 编辑区的示例啊
const handleCreated = (editor) => {
  editorRef.value = editor // editor实例
}

**Comment by wangfupeng1988** [comment]
@Corgis 参考这里 https://www.wangeditor.com/v5/toolbar-config.html#getconfig ，如果获取不到就在 setTimeout 中获取
