### ISSUE TITLE
V5.1.9报错

### ISSUE THREAD

**Issue by yuyinws** [wangeditor-team/wangEditor-for-vue3#9]
V5.1.9会报以下错误：
The requested module '/node_modules/.vite/deps/@wangeditor_editor-for-vue.js?v=c9b4b35f' does not provide an export named 'getEditor' (at Editor.vue:24:1)

提供的demo可复现这个问题。
https://github.com/liuqh0609/editor-vue3-demo

> 这个demo的yarn.lock锁了5.1.8版本，需要手动升级一下才能复现这个问题

**Comment by wangfupeng1988** [comment]
正在修改文档，稍等。改完了我在这里回复你。

**Comment by yuyinws** [comment]
> 

已看到文档 感谢回复
